# Generated by Django 5.1.3 on 2026-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("puesto", models.CharField(max_length=100, verbose_name="Puesto")),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("TI", "Tecnologías de la Información"),
                            ("RH", "Recursos Humanos"),
                            ("VEN", "Ventas"),
                            ("MKT", "Marketing"),
                            ("FIN", "Finanzas"),
                            ("OPE", "Operaciones"),
                        ],
                        default="TI",
                        max_length=3,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario"
                    ),
                ),
                (
                    "fecha_contratacion",
                    models.DateField(verbose_name="Fecha de contratación"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["-created_at"],
            },
        ),
    ]
